[package]
name = "userstyles-manager"
version = "0.1.0"
authors = ["Christian Dürr <contact@christianduerr.com>"]

[dependencies]
error-chain = "0.10.0"
reqwest = "0.7.2"
json = "0.11.9"
toml = "0.4.5"

[dev-dependencies]
tempfile = "2.1.6"
